// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2Nkf971G7LFfDamAxYs9wYx-CPkl1hY',
    appId: '1:896556017355:android:857c16654b1fdd62c6dd4e',
    messagingSenderId: '896556017355',
    projectId: 'eye-one-e8197',
    databaseURL: 'https://eye-one-e8197-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eye-one-e8197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrlM7AWtBUvXav7uDP0gPTcNT3h1pQYIw',
    appId: '1:896556017355:ios:9c5f0b103d7fcb8ec6dd4e',
    messagingSenderId: '896556017355',
    projectId: 'eye-one-e8197',
    databaseURL: 'https://eye-one-e8197-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eye-one-e8197.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

}